#!/usr/bin/python3

import os
import subprocess
import string
import re
import json

lcodes = sorted([x[:-3] for x in os.listdir('po') if x[-3:] == ".po"])


def get_lang(lcode):
    cmd = "isoquery -i 639-2 " + lcode[0:2]
    out = subprocess.check_output(cmd.split()).strip().decode()

    longname = out.split('\t')[3]
    shortname = longname.split()[0].strip(',;')

    return shortname

def percent_done(lcode):
    cmd = "msgfmt --statistics po/%s.po" % lcode
    out = subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT)

    tokens = out.split()
    translated = int(tokens[0])

    try:
        untranslated = int(tokens[3])
    except IndexError:
        untranslated = 0

    percent = int(100 * translated / (translated + untranslated))

    return percent

def get_translator(lcode):
    with open("po/%s.po" % lcode, 'r') as fl:
        for line in fl.readlines():
            match = re.search("^\"Last-Translator: ([^<]+)", line)
            if match and "FULL NAME" not in match.group(1):
                return match.group(1)

    return ""

stats = []
for lcode in lcodes:
    stats.append({
        'code': lcode,
        'language': get_lang(lcode),
        'percent': percent_done(lcode),
        'translator': get_translator(lcode),
    })

stats = sorted(stats, key=lambda x: x['language'])

print(json.dumps({'polist': stats}, sort_keys=True, indent=4))
